### ISSUE TITLE
Lancer hors docker

### ISSUE THREAD

**Issue by kepon85** [colibris-xyz/warmupmailserver#28]
Salut @tms0,

J'aurai souhaiter lancer warmupmailserver hors docker (parce que je n'ai pas d'infra docker, en monter une pour ça c'est peut être pas nessécaire...) 

Mais voilà quand je tente de le lancer voici ce que j’obtiens :

```
user@wam:~/tmp/warmupmailserver/src$ node index.js 
/home/david/tmp/warmupmailserver/src/index.js:1
import logger from './logger.js'
       ^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Alors je suis un débutant en node donc j'ai probablement pas tout compris, peut être qu'il y a une histoire de PATH, parce que le fichier logger.js existe bien à l’endroit ou je tente de lancer la chose : 

```
user@wam:~/tmp/warmupmailserver/src$ ls
dataset.js  logger.js             mailserver-sender.js  settings.default.json
index.js    mailbox-processor.js  package.json          settings.js
```

Merci,
David (kepon des CHATONS)

**Comment by tms0** [comment]
Hello @kepon85,

Le projet utilise des [modules "ECMAScript"](https://nodejs.org/api/esm.html#modules-ecmascript-modules). C'est automatiquement activé par la ligne `"type": "module"`dans le [package.json](https://github.com/colibris-xyz/warmupmailserver/blob/main/package.json#L7).

A mon avis, tu es sur une très vieille version de Node.js qui ne gère pas ce type de modules. Tu peux me donner ta version ?

**Comment by kepon85** [comment]
Effectivement j'étais en version v10.19.0 
Mais après un upgrade en v18 j'ai le même problème. Mais peut être que j'ai loupé un truc : 

```
david@dadell:~/tmp/warmupmailserver/app$ ls 
data  node_modules  package.json  src  yarn.lock
david@dadell:~/tmp/warmupmailserver/app$ yarn install --immutable
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.34s.
david@dadell:~/tmp/warmupmailserver/app$ node src/index.js 
(node:12900) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/david/tmp/warmupmailserver/app/src/index.js:1
import logger from './logger.js'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1040:15)
    at Module._compile (node:internal/modules/cjs/loader:1076:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v18.4.0
```

J'ai essayé de reproduire ce qui se passe dans le  https://github.com/colibris-xyz/warmupmailserver/blob/main/Dockerfile pour les dépendances / copie de fichier

**Comment by tms0** [comment]
C'est étrange ce warning, parce que le "type" est bien à "module" dans le package.json.
Normalement, pour le lancer hors Docker, tu n'as pas grand chose à faire :

```
$ git clone https://github.com/colibris-xyz/warmupmailserver.git
$ cd warmupmailserver
$ yarn install
$ SETTINGS_FILE_PATH=$(pwd)/settings.json node src/index.js
```

(En n'oubliant pas de créer le fichier settings.json)

**Comment by kepon85** [comment]
Autant pour moi, avec tes commandes ça fonctionne correctement... Je n'étais peut être pas dans le bon à l’exécution de yarn !
Merci
C'est TOP ton outil.
